CREATE TABLE IF NOT EXISTS person_tb(

id SERIAL PRIMARY KEY NOT NULL,
complete_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
cpf VARCHAR(11) NOT NULL UNIQUE,
rg VARCHAR(10) NOT NULL UNIQUE,
gender VARCHAR(6) NOT NULL,
cellphone VARCHAR(11) NOT NULL UNIQUE,
cep VARCHAR(8) NOT NULL,
address VARCHAR(60) NOT NULL,
number INTEGER NOT NULL,
complement VARCHAR(30) NOT NULL,
city VARCHAR(30) NOT NULL,
district VARCHAR(30) NOT NULL,
state VARCHAR(30) NOT NULL,
country VARCHAR(30) NOT NULL

)